export const stateCityMap: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Adoni", "Amadalavalasa", "Amalapuram", "Anakapalle", "Anantapur",
    "Bapatla", "Bheemunipatnam", "Bhimavaram", "Bobbili", "Chilakaluripet",
    "Chittoor", "Dharmavaram", "Eluru", "Gajuwaka", "Guntakal", "Guntur",
    "Hindupur", "Jaganmohan Reddy Nagar", "Jaggayyapeta", "Jammalamadugu",
    "Kadapa", "Kakinada", "Kandukur", "Kavali", "Kovur", "Kurnool",
    "Macherla", "Machilipatnam", "Madanapalle", "Mandapeta", "Markapur",
    "Nagari", "Narasaraopet", "Narasapuram", "Narsapur", "Nellore",
    "Nidadavolu", "Ongole", "Palacole", "Palasa Kasibugga", "Parvathipuram",
    "Pedana", "Proddatur", "Punganur", "Puttur", "Rajahmundry", "Rajam",
    "Rajampet", "Ramachandrapuram", "Rayachoti", "Rayadurg", "Repalle",
    "Salur", "Samalkot", "Sattenapalle", "Srikakulam", "Srikalahasti",
    "Sullurpeta", "Tadepalligudem", "Tadipatri", "Tanuku", "Tenali",
    "Tirupati", "Tiruvuru", "Tuni", "Uravakonda", "Venkatagiri",
    "Vijayawada", "Vinukonda", "Visakhapatnam", "Vizianagaram", "Yemmiganur",
  ],
  "Arunachal Pradesh": [
    "Along", "Anini", "Basar", "Bomdila", "Changlang", "Daporijo",
    "Deomali", "Itanagar", "Jairampur", "Khonsa", "Longding", "Miao",
    "Naharlagun", "Namsai", "Pasighat", "Roing", "Seppa", "Tawang",
    "Tezu", "Yingkiong", "Ziro",
  ],
  "Assam": [
    "Abhayapuri", "Barpeta", "Barpeta Road", "Bongaigaon", "Bokajan",
    "Bokakhat", "Chirang", "Dergaon", "Dhemaji", "Dhubri", "Dibrugarh",
    "Diphu", "Dispur", "Duliajan", "Goalpara", "Golaghat", "Guwahati",
    "Haflong", "Hailakandi", "Hojai", "Howraghat", "Jorhat", "Karimganj",
    "Kokrajhar", "Lanka", "Lakhimpur", "Lumding", "Mangaldoi", "Margherita",
    "Mariani", "Marigaon", "Nagaon", "Nalbari", "Namrup", "North Lakhimpur",
    "Rangia", "Sibsagar", "Silchar", "Sivasagar", "Sonari", "Tezpur",
    "Tinsukia", "Titabar",
  ],
  "Bihar": [
    "Ara", "Araria", "Arrah", "Arwal", "Aurangabad", "Bagaha", "Banka",
    "Begusarai", "Bettiah", "Bhagalpur", "Bihar Sharif", "Bikramganj",
    "Buxar", "Chhapra", "Darbhanga", "Dehri", "Dumraon", "Forbesganj",
    "Gaya", "Gopalganj", "Hajipur", "Jahanabad", "Jamui", "Jehanabad",
    "Jhanjharpur", "Katihar", "Kishanganj", "Lakhisarai", "Madhepura",
    "Madhubani", "Maner", "Manihari", "Marhaura", "Masaurhi", "Mohania",
    "Mokameh", "Monghyr", "Motihari", "Motipur", "Munger", "Muzaffarpur",
    "Nalanda", "Naugachhia", "Nawada", "Patna", "Purnia", "Rafiganj",
    "Rajgir", "Raxaul", "Saharsa", "Samastipur", "Sasaram", "Sheikhpura",
    "Sheohar", "Sitamarhi", "Siwan", "Supaul", "Vaishali",
  ],
  "Chhattisgarh": [
    "Ambikapur", "Bhatapara", "Bhilai", "Bilaspur", "Chirmiri", "Dalli-Rajhara",
    "Dhamtari", "Dongargarh", "Durg", "Jagdalpur", "Janjgir", "Kanker",
    "Kawardha", "Kondagaon", "Korba", "Mahasamund", "Mungeli", "Naila Janjgir",
    "Raigarh", "Raipur", "Rajnandgaon", "Sakti", "Saraipali", "Tilda Newra",
  ],
  "Goa": [
    "Aldona", "Bicholim", "Calangute", "Candolim", "Canacona", "Colva",
    "Cortalim", "Cuncolim", "Curchorem", "Mapusa", "Margao", "Mormugao",
    "Panaji", "Pernem", "Ponda", "Quepem", "Sanquelim", "Sanguem",
    "Valpoi", "Vasco da Gama",
  ],
  "Gujarat": [
    "Ahmedabad", "Amreli", "Anand", "Anjar", "Anklesvar", "Bharuch",
    "Bhavnagar", "Bhuj", "Botad", "Chandkheda", "Chhota Udaipur",
    "Dahod", "Deesa", "Dhoraji", "Gandhinagar", "Gandhidham", "Godhra",
    "Gondal", "Himatnagar", "Jamnagar", "Junagadh", "Kadi", "Kalol",
    "Khambhat", "Kutch", "Mahuva", "Mehsana", "Modasa", "Morbi",
    "Nadiad", "Navsari", "Palanpur", "Patan", "Porbandar", "Rajkot",
    "Rajpipla", "Sanand", "Sidhpur", "Surat", "Surendranagar",
    "Unjha", "Vadodara", "Valsad", "Veraval", "Viramgam", "Wankaner",
  ],
  "Haryana": [
    "Ambala", "Bahadurgarh", "Bhiwani", "Charkhi Dadri", "Faridabad",
    "Fatehabad", "Gurgaon", "Hansi", "Hisar", "Jhajjar", "Jind",
    "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Narnaul",
    "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak",
    "Sirsa", "Sonipat", "Thanesar", "Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Baddi", "Baijnath", "Bilaspur", "Chamba", "Dalhousie", "Dharamsala",
    "Hamirpur", "Kangra", "Kasauli", "Kullu", "Manali", "Mandi",
    "Nahan", "Nurpur", "Palampur", "Parwanoo", "Rampur", "Shimla",
    "Solan", "Sundernagar", "Una",
  ],
  "Jharkhand": [
    "Adityapur", "Barauni", "Bokaro", "Chaibasa", "Chirkunda", "Deoghar",
    "Dhanbad", "Dumka", "Ghatshila", "Giridih", "Godda", "Hazaribag",
    "Jamshedpur", "Jharia", "Jugsalai", "Lohardaga", "Madhupur",
    "Medininagar", "Mihijam", "Musabani", "Pakur", "Phusro", "Ramgarh",
    "Ranchi", "Sahibganj", "Sindri", "Tenu dam-cum-Kathhara",
  ],
  "Karnataka": [
    "Afzalpur", "Arsikere", "Bagalkot", "Ballari", "Bangalore Rural",
    "Bangarpet", "Belagavi", "Bengaluru", "Bidar", "Chikkaballapur",
    "Chikkamagaluru", "Chitradurga", "Davanagere", "Dharwad", "Gadag",
    "Gangawati", "Gokak", "Gulbarga", "Hassan", "Haveri", "Hiriyur",
    "Hospet", "Hubballi", "Kalaburagi", "Karwar", "Kolar", "Koppal",
    "Kushalnagar", "Madikeri", "Mandya", "Mangaluru", "Mysuru",
    "Nanjangud", "Puttur", "Raichur", "Ramanagara", "Robertson Pet",
    "Sagara", "Shimoga", "Shivamogga", "Sindgi", "Sirsi", "Sira",
    "Tarikere", "Tumakuru", "Udupi", "Vijayapura", "Yadgir",
  ],
  "Kerala": [
    "Adoor", "Alappuzha", "Aluva", "Angamaly", "Attingal", "Chalakudy",
    "Changanacherry", "Cherthala", "Chittur-Thathamangalam", "Ernakulam",
    "Ettumanoor", "Guruvayur", "Idukki", "Irinjalakuda", "Kalpetta",
    "Kannur", "Kasaragod", "Kochi", "Kodungallur", "Kollam", "Kottayam",
    "Kozhikode", "Kunnamkulam", "Malappuram", "Manjeri", "Mattanur",
    "Mavelikkara", "Muvattupuzha", "Nedumangad", "Neyyattinkara",
    "Nilambur", "Ottappalam", "Palakkad", "Pathanamthitta", "Ponnani",
    "Punalur", "Thalassery", "Thiruvananthapuram", "Thrissur", "Tirur",
    "Tiruvalla", "Vaikom", "Vatakara",
  ],
  "Madhya Pradesh": [
    "Ashok Nagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal",
    "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas",
    "Dhar", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore",
    "Itarsi", "Jabalpur", "Katni", "Khargone", "Khandwa", "Maihar",
    "Mandla", "Mandsaur", "Morena", "Murwara", "Nagda", "Narsinghpur",
    "Neemuch", "Panna", "Pithampur", "Raisen", "Rajgarh", "Ratlam",
    "Rewa", "Sagar", "Sarni", "Satna", "Sehore", "Seoni", "Shahdol",
    "Shajapur", "Sheopur", "Shivpuri", "Singrauli", "Tikamgarh",
    "Ujjain", "Umaria", "Vidisha",
  ],
  "Maharashtra": [
    "Ahmednagar", "Akola", "Akot", "Alibag", "Amravati", "Ambarnath",
    "Aurangabad", "Badlapur", "Baramati", "Beed", "Bhandara", "Bhiwandi",
    "Buldhana", "Chandrapur", "Chiplun", "Dhule", "Dombivli", "Gondia",
    "Ichalkaranji", "Jalgaon", "Jalna", "Kalyan", "Karad", "Khopoli",
    "Kolhapur", "Kopargaon", "Kudal", "Latur", "Lonavala", "Malegaon",
    "Mangaon", "Miraj", "Mumbai", "Murbad", "Nagpur", "Nanded",
    "Nandurbar", "Nashik", "Navi Mumbai", "Osmanabad", "Palghar",
    "Pandharpur", "Panvel", "Parbhani", "Pen", "Pimpri-Chinchwad",
    "Pune", "Pusad", "Raigad", "Ratnagiri", "Sangli", "Satara",
    "Shirdi", "Sinnar", "Solapur", "Thane", "Tumsar", "Udgir",
    "Ulhasnagar", "Vasai-Virar", "Wardha", "Washim", "Yavatmal",
  ],
  "Manipur": [
    "Bishnupur", "Churachandpur", "Imphal", "Jiribam", "Kakching",
    "Kangpokpi", "Lilong", "Mayang Imphal", "Moirang", "Moreh",
    "Nambol", "Senapati", "Thoubal", "Ukhrul",
  ],
  "Meghalaya": [
    "Baghmara", "Cherrapunjee", "Jowai", "Mairang", "Mankachar",
    "Nongpoh", "Nongstoin", "Resubelpara", "Shillong", "Tura",
    "Williamnagar",
  ],
  "Mizoram": [
    "Aizawl", "Bairabi", "Champhai", "Hnahthial", "Kolasib", "Lawngtlai",
    "Lunglei", "Mamit", "Saiha", "Saitual", "Serchhip",
  ],
  "Nagaland": [
    "Dimapur", "Kohima", "Longleng", "Mokokchung", "Mon", "Peren",
    "Phek", "Tuensang", "Wokha", "Zunheboto",
  ],
  "Odisha": [
    "Anugul", "Balangir", "Balasore", "Barbil", "Bargarh", "Baripada",
    "Berhampur", "Bhadrak", "Bhawanipatna", "Bhubaneswar", "Brahmapur",
    "Burla", "Cuttack", "Dhenkanal", "Jharsuguda", "Kendrapara",
    "Kendujhar", "Koraput", "Malkangiri", "Nabarangapur", "Paradip",
    "Phulabani", "Puri", "Rayagada", "Rourkela", "Sambalpur",
    "Soro", "Sunabeda", "Talcher", "Titlagarh",
  ],
  "Punjab": [
    "Abohar", "Amritsar", "Barnala", "Batala", "Bathinda", "Dhuri",
    "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gobindgarh",
    "Gurdaspur", "Hoshiarpur", "Jagraon", "Jalandhar", "Kapurthala",
    "Khanna", "Kharar", "Kot Kapura", "Longowal", "Ludhiana",
    "Malerkotla", "Mansa", "Moga", "Mohali", "Morinda", "Muktsar",
    "Nabha", "Nangal", "Nakodar", "Pathankot", "Patiala", "Phagwara",
    "Rajpura", "Rupnagar", "Sangrur", "Sirhind-Fatehgarh Sahib",
    "Sujanpur", "Sunam", "Tarn Taran",
  ],
  "Rajasthan": [
    "Ajmer", "Alwar", "Bandikui", "Banswara", "Baran", "Barmer",
    "Beawar", "Bhilwara", "Bharatpur", "Bikaner", "Bundi", "Chittorgarh",
    "Churu", "Dausa", "Dhaulpur", "Dungarpur", "Ganganagar", "Gangapur City",
    "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar",
    "Jhunjhunu", "Jodhpur", "Karauli", "Kishangarh", "Kota", "Makrana",
    "Nagaur", "Nawalgarh", "Neem ka Thana", "Pali", "Phalodi",
    "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar", "Sirohi",
    "Sri Ganganagar", "Sujangarh", "Sumerpur", "Suratgarh", "Tonk",
    "Udaipur",
  ],
  "Sikkim": [
    "Gangtok", "Geyzing", "Gyalshing", "Jorethang", "Mangan",
    "Namchi", "Nayabazar", "Rangpo", "Ravangla", "Singtam",
  ],
  "Tamil Nadu": [
    "Arakkonam", "Ariyalur", "Aruppukkottai", "Attur", "Avanashi",
    "Chennai", "Chengalpattu", "Chidambaram", "Coimbatore", "Cuddalore",
    "Coonoor", "Dharmapuri", "Dindigul", "Erode", "Gudiyatham",
    "Gudalur", "Gobichettipalayam", "Harur", "Hosur", "Kancheepuram",
    "Karaikudi", "Karur", "Kinathukadavu", "Kodaikanal", "Kovilpatti",
    "Krishnagiri", "Kumbakonam", "Madurai", "Manamadurai", "Mannargudi",
    "Mettupalayam", "Mettur", "Musiri", "Nagapattinam", "Nagercoil",
    "Namakkal", "Natham", "Ooty", "Palani", "Palladam", "Paramakudi",
    "Pattukkottai", "Perambalur", "Pollachi", "Pudukkottai", "Rajapalayam",
    "Ranipet", "Ramanathapuram", "Salem", "Sankarankoil", "Sivaganga",
    "Sivakasi", "Tenkasi", "Thanjavur", "Thoothukudi", "Tiruchengode",
    "Tiruchirappalli", "Tirunelveli", "Tiruppur", "Tiruvallur",
    "Tiruvannamalai", "Tiruvottiyur", "Udumalaipettai", "Udhagamandalam",
    "Vellore", "Viluppuram", "Virudhunagar",
  ],
  "Telangana": [
    "Adilabad", "Bhongir", "Bodhan", "Gadwal", "Hyderabad",
    "Jagtial", "Jangaon", "Kamareddy", "Karimnagar", "Khammam",
    "Kodad", "Kothagudem", "Kyathampalle", "Mahabubnagar", "Mahbubnagar",
    "Mancherial", "Mandamarri", "Metpally", "Miryalaguda",
    "Nalgonda", "Narayanpet", "Nirmal", "Nizamabad", "Palwancha",
    "Ramagundam", "Sangareddy", "Secunderabad", "Siddipet", "Sircilla",
    "Suryapet", "Tandur", "Vikarabad", "Wanaparthy", "Warangal",
    "Yellandu",
  ],
  "Tripura": [
    "Agartala", "Ambassa", "Belonia", "Dharmanagar", "Kailashahar",
    "Kamalpur", "Khowai", "Sabroom", "Sonamura", "Udaipur",
  ],
  "Uttar Pradesh": [
    "Agra", "Aligarh", "Allahabad", "Amroha", "Azamgarh", "Bahraich",
    "Ballia", "Banda", "Bareilly", "Basti", "Bijnor", "Bulandshahr",
    "Chandausi", "Deoria", "Etah", "Etawah", "Faizabad", "Farrukhabad",
    "Fatehpur", "Firozabad", "Ghaziabad", "Ghazipur", "Gonda",
    "Gorakhpur", "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun",
    "Jaunpur", "Jhansi", "Kannauj", "Kanpur", "Kasganj", "Kaushambi",
    "Khurja", "Lakhimpur Kheri", "Lalitpur", "Lucknow", "Mathura",
    "Mau", "Meerut", "Mirzapur", "Modinagar", "Moradabad", "Muzaffarnagar",
    "Noida", "Orai", "Pilibhit", "Prayagraj", "Rae Bareli", "Rampur",
    "Saharanpur", "Sambhal", "Shahjahanpur", "Shikohabad", "Sitapur",
    "Sultanpur", "Unnao", "Varanasi",
  ],
  "Uttarakhand": [
    "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haldwani",
    "Haridwar", "Jaspur", "Kashipur", "Kichha", "Kotdwar", "Manglaur",
    "Mussoorie", "Nainital", "Pauri", "Pithoragarh", "Rishikesh",
    "Roorkee", "Rudrapur", "Tehri", "Uttarkashi",
  ],
  "West Bengal": [
    "Alipurduar", "Asansol", "Bahrampur", "Balurghat", "Bankura",
    "Bardhaman", "Barasat", "Basirhat", "Birnagar", "Bishnupur",
    "Chandannagar", "Cooch Behar", "Darjeeling", "Dhulian", "Durgapur",
    "Gangarampur", "Haldia", "Howrah", "Jalpaiguri", "Jangipur",
    "Jhargram", "Kalimpong", "Kharagpur", "Kolkata", "Krishnanagar",
    "Malda", "Medinipur", "Murshidabad", "Nabadwip", "Nalhati",
    "Purulia", "Raiganj", "Rajarhat", "Ranaghat", "Siliguri",
    "Sonamukhi", "Taki",
  ],
  // Union Territories
  "Andaman and Nicobar Islands": [
    "Bamboo Flat", "Diglipur", "Mayabunder", "Port Blair", "Rangat",
  ],
  "Chandigarh": ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Amli", "Daman", "Diu", "Naroli", "Silvassa",
  ],
  "Delhi": [
    "Burari", "Civil Lines", "Connaught Place", "Darya Ganj", "Dashrath Puri",
    "Dilshad Garden", "Dwarka", "Geeta Colony", "Greater Kailash", "Janakpuri",
    "Karol Bagh", "Laxmi Nagar", "Mehrauli", "Model Town", "Mustafabad",
    "Najafgarh", "Nangloi Jat", "New Delhi", "Okhla", "Pahar Ganj",
    "Pitampura", "Preet Vihar", "Punjabi Bagh", "Rohini", "Saket",
    "Seelampur", "Shahdara", "Shalimar Bagh", "Tilak Nagar", "Vasant Kunj",
    "Vasant Vihar", "Vikaspuri",
  ],
  "Jammu and Kashmir": [
    "Anantnag", "Awantipora", "Baramulla", "Batote", "Bhaderwah",
    "Bijbehara", "Doda", "Handwara", "Jammu", "Kathua", "Kishtwar",
    "Kulgam", "Kupwara", "Pampore", "Pattan", "Pulwama", "Punch",
    "Rajouri", "Ramban", "Shopian", "Sopore", "Srinagar", "Sunderbani",
    "Udhampur",
  ],
  "Ladakh": [
    "Diskit", "Kargil", "Leh", "Nyoma", "Padum", "Turtuk",
  ],
  "Lakshadweep": [
    "Agatti", "Amini", "Andrott", "Chetlat", "Kavaratti", "Kiltan",
    "Minicoy",
  ],
  "Puducherry": [
    "Karaikal", "Mahe", "Ozhukarai", "Puducherry", "Villianur", "Yanam",
  ],
};
